### ISSUE TITLE
Create ArticleLikes Model

### ISSUE THREAD

**Issue by bsuro10** [MaayanMordehai/CollegeWebProject#6]
Check how to implement many-to-many relationship using ArticleLikes model
The connection is between profile table and Article table

> Ori Granot

**Comment by bsuro10** [comment]
Check out https://www.entityframeworktutorial.net/efcore/configure-many-to-many-relationship-in-ef-core.aspx for more details

**Comment by ghost** [comment]
Check out https://stackoverflow.com/questions/18648600/many-to-many-mapping-using-data-annotations for example with annotations

**Comment by bsuro10** [comment]
> Check out https://stackoverflow.com/questions/18648600/many-to-many-mapping-using-data-annotations for example with annotations

I talked with the teacher and he will do an example next week, he said it should be simpler than my reference
