### ISSUE TITLE
UserController - PostEditUser users with duplicates email

### ISSUE THREAD

**Issue by bsuro10** [MaayanMordehai/CollegeWebProject#74]

**Comment by ghost** [comment]
Check again if needed, I got an error from server when tried to edit to email that exists... i think you might have worked on not updated branch. this check was added in commit #69 
@bsuro10

**Comment by bsuro10** [comment]
@MaayanMordehai 
When you edit a profile and change your email address to existing one - it changes the view but not the DB

We need to return an error
